version: '3.8'

services:
  app:
    build: .
    image: hng-country-api
    container_name: hng_country_app
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:soHN2ZyKYZrjhHzGRW0G66rR3zwAPDQYMRWqEao4tS4=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=hng
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    volumes:
      - ./:/var/www
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 3

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: hng
    ports:
      - "33060:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:




